# Generated by Django 4.1.6 on 2023-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('twitter', models.CharField(max_length=200, null=True)),
                ('joined_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
